### ISSUE TITLE
Newsletter link returns 404 error

### ISSUE THREAD

**Issue by anderspeders** [Code4SA/old-code4sa.github.io#13]
http://code4sa.org/newsletter <-- I believe that this returns a 404 error

**Comment by adieyal** [comment]
Thanks for the heads-up. Looking into it now

**Comment by j-norwood-young** [comment]
It's because of the move to Github Pages. Not sure how you'd do  a forward in github.io?

**Comment by j-norwood-young** [comment]
Made it a page.
