### ISSUE TITLE
Add Naked Data archive to website

### ISSUE THREAD

**Issue by j-norwood-young** [Code4SA/old-code4sa.github.io#17]
http://us8.campaign-archive1.com/home/?u=11977a67604b965526b63ee6e&id=0852ce7e74

**Comment by j-norwood-young** [comment]
More info from @longhotsummer: http://kb.mailchimp.com/campaigns/archives/set-up-your-campaign-archive

**Comment by longhotsummer** [comment]
At the very least we should link to the archive. There's gold in them thar emails, let's not lose them.

**Comment by longhotsummer** [comment]
I have added the newsletter's RSS feed to the site metadata.

**Comment by longhotsummer** [comment]
This was done a while ago.
