### ISSUE TITLE
Living Wage link doesn't work

### ISSUE THREAD

**Issue by drewrwilson** [Code4SA/old-code4sa.github.io#28]
Hello! The link on index.html to living-wage.code4sa.org doesn't work. I get a 404 from github with that url. The calculator sounds like a cool project!

**Comment by longhotsummer** [comment]
This has been fixed, thanks for letting us know.

We're building up a story around that link, so keep a watch on our blog.

**Comment by drewrwilson** [comment]
Very cool! Looking forward to seeing it. :)
