### ISSUE TITLE
Academy Banner and Text Changes

### ISSUE THREAD

**Issue by Lenina210** [Code4SA/old-code4sa.github.io#73]
Need to change the Banner text on Code4SA and the Academy website. 

code4sa.org - banner needs to change from: 

"Code for South Africa is launching Africa's first data journalism school in February 2016. Find out more  " 
to
"Code for South Africa launched Africa's first data journalism academy in February 2016. Find out more "

academy.code4sa.org - banner needs to change from: 

"Code for South Africa is launching Africa's first data journalism school in February 2016." 
to
"Code for South Africa launched Africa's first data journalism academy in February 2016."
1. The 'school' webpage (http://code4sa.org/school/) should be deleted as we are no longer using the term school and it's confusing if users land on there. 
2. The Banner on code4sa.org should no longer link to the school page but to the new Academy website. 
3. In the long text on the Academy website, all references to 'school' should change to Academy, except the last paragraph which references 'School of Data'.

**Comment by guushoekman** [comment]
In order to change all references to 'school' we'll need a new email address as well (it's currently dataschool@code4sa.org)

**Comment by longhotsummer** [comment]
@guushoekman i'm checking on what the email address should be.

**Comment by longhotsummer** [comment]
It'll be academy@code4sa.org, that'll be working shortly.
